// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnilyapvhhygfzcdxqjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaWx5YXB2aGh5Z2Z6Y2R4cWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0Mzc4NzYsImV4cCI6MjA5MTAxMzg3Nn0.A_fljSEuPD9ezUTBC9jBvQu-M3dtCk-fDfwm5CV07c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});